import 'lazysizes'
import 'lazysizes/plugins/print/ls.print'
import './classes/ScrollDirection'
import './classes/ButtonSeoClick'
import './classes/Header'
import './classes/Animation'
import './classes/ImageBlock'
